spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        driver-class-name: org.h2.Driver
        username: sa

    jpa:
        #show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true

    data:
        redis:
            host: localhost
            port: 6379


debug: true

cache:
    expire:
        saveInDBMinutes: 10
        redisTTLSpareMinutes: 1


logging:
    level:
        com.example.cacheExample: debug
